### ISSUE TITLE
Feature Request:  proxy attribute

### ISSUE THREAD

**Issue by markfaine** [antoineco/aco-ulyaoth#8]
Can you add options for a proxy to add to the yum repo file.  

Something like: 
proxy=http://mycache.mydomain.com:3128

Optionally, couldn't hurt to add:
proxy_username=yum-user
proxy_password=qwerty

**Comment by antoineco** [comment]
I can do that

**Comment by antoineco** [comment]
Released in [v1.1.4](https://forge.puppet.com/aco/ulyaoth/1.1.4/changelog)
